
const onUncaughtException = (err, origin) => {
};

module.exports = onUncaughtException;